AMBARI-22030. OOZIE/OOZIE_SERVER restart failed saying AttributeError: 'NoneType' object has no attribute 'upper' during EU (ncole)
(cherry picked from commit fb9ef3c39f0db8a32688c669f95a6b5329b5e844)

Change-Id: If9ffa65213b3f14fc69c7f7087b7d3c86fc2d958